status: wip
context:
  contact-config: '@contact'
  article-config:
    article:
      article-hide-small: true
      article-title: "Get in touch"
      article-title-i18n: "panel4.article.title"
      article-title-tag: "h3"
      article-body: "<p>For questions don't hesitate and contact us.</p>"
      article-body-i18n: "panel4.article.body"
      article-hide-footer: true
  gamemaster-config: '@gamemaster'
i18n:
  'de-DE':
    'panel4.article.title': "Kontaktiere uns"
    'panel4.article.body': "<p>Bei Fragen kontaktiere uns.</p>"
  'en-EN':
    'panel4.article.title': "Get in touch"
    'panel4.article.body': "<p>For questions don't hesitate and contact us.</p>"