version: "3"

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 90:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.1-fpm-alpine
    volumes:
      - ./src:/usr/share/nginx/html
      - ./src:/rest

  redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
    volumes:
      - ./docker/volumes/redis:/var/lib/redis

  memcached:
    image: memcached:1.4-alpine
    ports:
      - 11211:11211

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025

  # mysql:{PHP_MAILER_HOST}
  #   image: mysql:5.7
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=pass
  #     - MYSQL_DATABASE=web
  #     - MYSQL_USER=web
  #     - MYSQL_PASSWORD=pass
  #   volumes:
  #     - ./docker/volumes/mysql:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:4.6
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_USER=web
  #     - PMA_PASSWORD=pass