version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "90:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    image: nginx:alpine
    links:
      - php
      - mail
    ports:
      - 80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./src:/var/www/vhost/webroot
    environment:
      VIRTUAL_HOST: web.vhost.test

  php:
    image: php:fpm-alpine
    ports:
      - "9000:9000"
    # links:
    #   - db
    volumes:
      - ./src:/var/www/vhost/webroot

  mail:
    image: occitech/alpine-mailhog
    ports:
      - 8025
    environment:
      VIRTUAL_HOST: mail.vhost.test
      VIRTUAL_PORT: 8025

  # db:
  #   image: mysql:latest
  #   volumes:
  #     - ./.data/db:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "password"
  #     MYSQL_DATABASE: whatever

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db
  #   environment:
  #     VIRTUAL_HOST: db.vhost.test