version: "3"

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 90:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.1-fpm-alpine
    volumes:
      - ./src:/usr/share/nginx/html