version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/share/nginx/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ./www:/usr/share/nginx/www
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
