status: prototype
context:
  link:
    link-href: "#"
    label:
      label-text: "Link Label Text"
      icon:
        icon-name: "arrow-right"
        icon-pos: "before"
        icon-class: "icon-xs"
