status: wip
context:
  article-config:
    article:
      article-hide-small: true
      article-title: "Infos"
      article-title-i18n: "panel2.article.title"
      article-title-tag: "h3"
      article-body: "<p>Pfarrei St. Johannes, Luzern</p><p>Samstag, 6. October 18</p><p>from 9 a.m. to 18 p.m.</p>"
      article-body-i18n: "panel2.article.body"
      article-hide-footer: true
  gamemaster-config: '@gamemaster'
i18n:
  'de-DE':
    'panel2.article.title': "Infos"
    'panel2.article.body': "<p>Der Luzerner Rollenspieltag findet am Samstag, 6. Oktober 2018, statt. Wir öffnen die Tore ab 12 Uhr, die ersten Spielrunden beginnen um 13 Uhr.</p><p>Spielzeiten: Samstag, 13 Uhr bis Sonntag, 1 Uhr<br />Eintritt: 5 Franken pro Person / für Spielleiter ist der Eintritt gratis<br />Adresse: Pfarrei St. Johannes, Schädrütistrasse 26, 6006 Luzern</p><p>Vom Bahnhof Luzern sind die Räumlichkeiten bequem in 15 Minuten erreichbar per Bus 8 (Würzenbachmatte) oder Bus 14 (Schlösslirain).</p><p>Wenn du von weiterher kommst und gerne stressfrei in Luzern übernachten möchtest, helfen wir dir gerne dabei deinen Aufenthalt zu planen. Melde dich doch bitte über das Kontaktformular.</p>"
  'en-EN':
    'panel2.article.title': "Infos"
    'panel2.article.body': "<p>Pfarrei St. Johannes, Luzern</p><p>Samstag, 6. October 18</p><p>from 9 a.m. to 18 p.m.</p>"