status: prototype
context:
  navigation-role: "navigation"
  navigation-class: "example-class"
  navigation-items:
    -
      link:
        link-href: "#"
        label:
          label-role: "note"
          label-text: "Nav 1"
          icon:
            icon-name: "arrow-right"
            icon-pos: "after"
            icon-class: "icon-xs"
      navigation-active: true
      navigation-role: "navigation"
    -
      link:
        link-href: "#"
        label:
          label-text: "Nav 2"
      navigation-role: "navigation"
      navigation-items:
        -
          link:
            link-href: "#"
            label:
              label-text: "Sub 1"
          navigation-role: "navigation"
        -
          link:
            link-href: "#"
            label:
              label-text: "Sub 2"
          navigation-role: "navigation"
    -
      link:
        link-href: "#"
        label:
          label-text: "Nav 3"
      navigation-role: "navigation"
