status: wip
context:
  figure:
    picture:
      picture-title: "Welcome to Luzerner Rollenspieltage"
      picture-i18n: ""
      picture-sources:
        -
          viewport: 600
          source: "https://picsum.photos/600/400/?random&blur"
        -
          viewport: 400
          source: "https://picsum.photos/480/320/?random&blur"
        -
          source: "https://picsum.photos/320/240/?random&blur"
      image:
        image-alt: "Welcome to Luzerner Rollenspieltage"
        image-i18n: ""
        # image-class: ""
        image-source: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        image-lazyload: "https://picsum.photos/2480/2048/?random&blur"
