# status: wip
context:
  button:
    button-class: "example-button-class"
    button-type: "submit"
    button-role: "button"
    label:
      label-text: "Form button"
      label-text-i18n: "button.label.text.demo"
i18n:
  'de-DE':
    'button.label.text.demo': "Form button (DE)"
  'en-EN':
    'button.label.text.demo': "Form button (EN)"
