status: prototype
context:
  input:
    label:
      label-for: "demo-input-1"
      label-text: "Demo Input Field 1"
      label-text-i18n: "label.text.demo"
    input-role: "input"
    # input-role: "checkbox"
    # input-role: "radio"
    input-type: "text"
    input-id: "demo-input-1"
    input-name: "demo[input-1]"
    input-placeholder: "Demo Input Field 1"
    input-i18n: "label.text.demo"
    input-class: "example-input-class"
    input-autocomplete: "input"
t18n:
  'de-DE':
    'label.text.demo': "Demo Input Field 1 (DE)"
  'en-EN':
    'label.text.demo': "Demo Input Field 1 (EN)"
