status: ready
context:
  textarea:
    label:
      label-for: "demo-textarea-1"
      label-text: "Demo Textarea Field 1"
      label-text-i18n: "textarea.label.text.demo"
    textarea-role: "textarea"
    textarea-id: "demo-textarea-1"
    textarea-name: "demo[textarea-1]"
    textarea-placeholder: "Demo Textarea Field 1"
    textarea-i18n: "textarea.label.text.demo"
    textarea-class: "example-textarea-class"
i18n:
  'de-DE':
    'textarea.label.text.demo': "Demo Textarea Field 1 (DE)"
  'en-EN':
    'textarea.label.text.demo': "Demo Textarea Field 1 (DE)"
