status: prototype
context:
  textarea:
    label:
      label-for: "demo-textarea-1"
      label-text: "Demo Textarea Field 1"
    textarea-role: "textarea"
    textarea-id: "demo-textarea-1"
    textarea-name: "demo[textarea-1]"
    textarea-placeholder: "Demo Textarea Field 1"
    textarea-class: "example-textarea-class col-m-6"
