status: published
context:
  step-1:
    form:
      form-name: "KeepMePosted"
      form-action: "http://localhost:3000/rest/form.json"
      form-method: "get"
      form-class: "step-1 keep-me-posted-step active"
      form-items:
        -
          fieldset:
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12"
                      input:
                        label:
                          label-for: "keep-me-posted-name"
                          label-text: "Your Firstname, Lastname"
                          label-text-i18n: "keep-me-posted.step-1.input.name"
                        input-id: "keep-me-posted-name"
                        input-name: "KeepMePosted[name]"
                        input-placeholder: "Your Firstname, Lastname"
                        input-i18n: "keep-me-posted.step-1.input.name"
                        input-required: true
                        input-class: ""
                        # Don't need for text > input-type: "text"
                        input-role: "input"
                        input-autocomplete: "name"
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12"
                      input:
                        label:
                          label-for: "keep-me-posted-email"
                          label-text: "Your Email"
                          label-text-i18n: "keep-me-posted.step-1.email.name"
                        input-id: "keep-me-posted-email"
                        input-name: "KeepMePosted[email]"
                        input-placeholder: "Your Email"
                        input-i18n: "keep-me-posted.step-1.email.name"
                        input-required: true
                        input-class: ""
                        input-type: "email"
                        input-role: "input"
                        input-autocomplete: "email"
        -
          fieldset:
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12 align-center"
                      button:
                        label:
                          label-text: "Tell me when registration opens"
                          label-text-i18n: "keep-me-posted.step-1.button.next"
                        button-class: "submit-group"
                        button-type: "submit"
                        button-role: "button"
  form-2:
    panel-class: "form-2 keep-me-posted-step"
    article:
      article-hide-small: true
      article-title: "Thank you for your interest."
      article-title-i18n: "keep-me-posted.form-2.article.title"
      article-title-tag: "h1"
      article-subtitle: "We'll keep you posted as soon as our registration for Gamers opens.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"
      article-subtitle-i18n: "keep-me-posted.form-2.article.subtitle"
i18n:
  'de-DE':
    'keep-me-posted.step-1.input.name': "Dein Vorname, Nachname"
    'keep-me-posted.step-1.input.name.error': "Bitte trage deinen Namen ein"
    'keep-me-posted.step-1.email.name': "Deine E-Mail"
    'keep-me-posted.step-1.input.email.error.1': "Bitte trage deine E-Mail ein"
    'keep-me-posted.step-1.input.email.error.2': "Die E-Mail sieht nicht korrekt aus"
    'keep-me-posted.step-1.button.next': "Gebt Bescheid wenn die Registrierung für Spieler öffnet"
  'en-EN':
    'keep-me-posted.step-1.input.name': "Your Firstname, Lastname"
    'keep-me-posted.step-1.input.name.error': "Please enter your Name"
    'keep-me-posted.step-1.email.name': "Your Email"
    'keep-me-posted.step-1.input.email.error.1': "Please enter your Email"
    'keep-me-posted.step-1.input.email.error.2': "Email doesn't look correct"
    'keep-me-posted.step-1.button.next': "Tell me when registration for Gamers opens"
