status: wip
context:
  step-2:
    panel-class: "step-2 keep-me-posted-step"
    article:
      article-hide-small: true
      article-title: "Thank you for your interest."
      article-title-i18n: "keep-me-posted.step-2.article.title"
      article-title-tag: "h1"
      article-subtitle: "We'll keep you posted as soon as our registration for Gamers opens.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"
      article-subtitle-i18n: "keep-me-posted.step-2.article.subtitle"
i18n:
  'de-DE':
    'keep-me-posted.step-2.article.title': "Vielen Dank für dein Interesse"
    'keep-me-posted.step-2.article.subtitle': "Wir werden dich informieren sobald die Registrierung für Spieler öffnet.<br />Beste Grüsse<br />Das Luzerner Rollenspieltage Team"
  'en-EN':
    'keep-me-posted.step-2.article.title': "Thank you for your interest."
    'keep-me-posted.step-2.article.subtitle': "We'll keep you posted as soon as our registration for Gamers opens.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"
