status: published
context:
  step-3:
    form:
      form-name: "Organization"
      # form-action: "http://localhost:3000/rest/form.json"
      # form-method: "get"
      form-action: "form.php"
      form-method: "post"
      form-class: "step-3 registration-step"
      form-items:
        -
          fieldset:
            fieldset-legend: "About the Organization"
            fieldset-legend-i18n: "registration.step-3.fieldset"
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12 form-group"
                      article:
                        article-hide-header: true
                        article-body: "<p>We like to offer up to 6 Slots each with 2 hours of game time. This should help Gamers to try different Games very easily. Please choose your prefered game slots:</p>"
                        article-body-i18n: "registration.step-3.article.slots"
                        article-hide-footer: true
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-4"
                      fieldset:
                        fieldset-legend: "Afternoon"
                        fieldset-legend-i18n: "registration.step-3.fieldset.time1"
                        fieldset-items:
                          -
                            group-row:
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-xs-12"
                                  input:
                                    label:
                                      label-for: "slot-1-3"
                                      label-text: "From 01:00 to 03:00 p.m."
                                      label-text-i18n: "registration.step-3.input.slot.1-3"
                                    input-id: "slot-1-3"
                                    input-name: "Organization[slot-1-3]"
                                    input-class: "slots"
                                    input-type: "checkbox"
                                    input-role: "checkbox"
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-xs-12"
                                  input:
                                    label:
                                      label-for: "slot-3-5"
                                      label-text: "From 03:00 to 05:00 p.m."
                                      label-text-i18n: "registration.step-3.input.slot.3-5"
                                    input-id: "slot-3-5"
                                    input-name: "Organization[slot-3-5]"
                                    input-class: "slots"
                                    input-type: "checkbox"
                                    input-role: "checkbox"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-4"
                      fieldset:
                        fieldset-legend: "Evening"
                        fieldset-legend-i18n: "registration.step-3.fieldset.time2"
                        fieldset-items:
                          -
                            group-row:
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-xs-12"
                                  input:
                                    label:
                                      label-for: "slot-5-7"
                                      label-text: "From 05:00 to 07:00 p.m."
                                      label-text-i18n: "registration.step-3.input.slot.5-7"
                                    input-id: "slot-5-7"
                                    input-name: "Organization[slot-5-7]"
                                    input-class: "slots"
                                    input-type: "checkbox"
                                    input-role: "checkbox"
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-xs-12"
                                  input:
                                    label:
                                      label-for: "slot-7-9"
                                      label-text: "From 07:00 to 09:00 p.m."
                                      label-text-i18n: "registration.step-3.input.slot.7-9"
                                    input-id: "slot-7-9"
                                    input-name: "Organization[slot-7-9]"
                                    input-class: "slots"
                                    input-type: "checkbox"
                                    input-role: "checkbox"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-4"
                      fieldset:
                        fieldset-legend: "Night"
                        fieldset-legend-i18n: "registration.step-3.fieldset.time3"
                        fieldset-items:
                          -
                            group-row:
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-xs-12"
                                  input:
                                    label:
                                      label-for: "slot-9-11"
                                      label-text: "From 09:00 to 11:00 p.m."
                                      label-text-i18n: "registration.step-3.input.slot.9-11"
                                    input-id: "slot-9-11"
                                    input-name: "Organization[slot-9-11]"
                                    input-class: "slots"
                                    input-type: "checkbox"
                                    input-role: "checkbox"
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-xs-12"
                                  input:
                                    label:
                                      label-for: "slot-11-1"
                                      label-text: "From 11:00 p.m to 01:00 a.m."
                                      label-text-i18n: "registration.step-3.input.slot.11-1"
                                    input-id: "slot-11-1"
                                    input-name: "Organization[slot-11-1]"
                                    input-class: "slots"
                                    input-type: "checkbox"
                                    input-role: "checkbox"
        -
          fieldset:
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-xs-12"
                      input:
                        label:
                          label-for: "coc"
                          label-text: "I have read and accept the <a href='./code-of-conduct.html' target='blank'>Code of Conduct</a>"
                          label-text-i18n: "registration.step-3.input.coc"
                        input-id: "coc"
                        input-name: "Organization[coc]"
                        input-required: true
                        input-class: ""
                        input-type: "checkbox"
                        input-role: "checkbox"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-xs-6"
                      button-link:
                        link:
                          label:
                            label-text: "Back to previous form"
                            label-text-i18n: "registration.step-3.button.previous"
                          link-class: "button-link back-link"
                          link-href: "#form-2"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-xs-6 align-right"
                      input:
                        input-name: "User[id]"
                        input-class: "hidden"
                        input-type: "hidden"
                      button:
                        label:
                          label-text: "Finish registration"
                          label-text-i18n: "registration.step-3.button.next"
                        button-class: "submit-group"
                        button-type: "submit"
                        button-role: "button"
i18n:
  'de-DE':
    'registration.step-3.fieldset': "Zwecks der Organisation"
    'registration.step-3.article.slots': "<p>Wir möchten bis zu 6 Slots mit je 2 Std. Spielzeit anbieten. Das soll den Spieler helfen verschiedene Spiele sehr einfach zu testen. Bitte wähle deine gewünschten Gameslots:</p>"
    'registration.step-3.fieldset.time1': "Nachmittag"
    'registration.step-3.fieldset.time2': "Abend"
    'registration.step-3.fieldset.time3': "Nacht"
    'registration.step-3.input.slot.1-3': "von 13 bis 15 Uhr"
    'registration.step-3.input.slot.3-5': "von 15 bis 17 Uhr"
    'registration.step-3.input.slot.5-7': "von 17 bis 19 Uhr"
    'registration.step-3.input.slot.7-9': "von 19 bis 21 Uhr"
    'registration.step-3.input.slot.9-11': "von 21 bis 23 Uhr"
    'registration.step-3.input.slot.11-1': "von 21 bis 1 Uhr"
    'registration.step-3.input.slot.error': "Bitte wähle mindestens einen Spiel Termin aus"
    'registration.step-3.button.previous': "Zurück zur vorherigen Form"
    'registration.step-3.button.next': "Registrierung abschliessen"
    'registration.step-3.input.coc': "Ich habe den <a href='./code-of-conduct.html' target='blank'>Code of Conduct</a> gelesen und aktzeptiere diesen"
    'registration.step-3.input.coc.error': "Bitte aktzeptiere unseren Code of Conduct"
  'en-EN':
    'registration.step-3.fieldset': "About the Organizations"
    'registration.step-3.article.slots': "<p>We like to offer up to 6 Slots each with 2 hours of game time. This should help Gamers to try different Games very easily. Please choose your prefered game slots:</p>"
    'registration.step-3.fieldset.time1': "Afternoon"
    'registration.step-3.fieldset.time2': "Evening"
    'registration.step-3.fieldset.time3': "Night"
    'registration.step-3.input.slot.1-3': "From 01:00 to 03:00 p.m."
    'registration.step-3.input.slot.3-5': "From 03:00 to 05:00 p.m."
    'registration.step-3.input.slot.5-7': "From 05:00 to 07:00 p.m."
    'registration.step-3.input.slot.7-9': "From 07:00 to 09:00 p.m."
    'registration.step-3.input.slot.9-11': "From 09:00 to 11:00 p.m."
    'registration.step-3.input.slot.11-1': "From 11:00 p.m. to 01:00 a.m."
    'registration.step-3.input.slot.error': "Please select at least one game slot"
    'registration.step-3.button.previous': "Back to previous form"
    'registration.step-3.button.next': "Finish registration"
    'registration.step-3.input.coc': "I have read and accept the <a href='./code-of-conduct.html' target='blank'>Code of Conduct</a>"
    'registration.step-3.input.coc.error': "Please accept our Code of Conduct"

