status: wip
context:
  step-4:
    panel-class: "step-4 registration-step"
    article:
      article-hide-small: true
      article-title: "Welcome Gamemaster"
      article-title-i18n: "registration.step-4.article.title"
      article-title-tag: "h3"
      article-subtitle: "Thank you very much for helping us making this event a special one for every role player. <br />We will check your registration and come back to you in the next couple of days.<br />Have a good time, till we meet again.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"
      article-subtitle-i18n: "registration.step-4.article.subtitle"
i18n:
  'de-DE':
    'registration.step-4.article.title': "Herzlich Willkommen als Spielleiter"
    'registration.step-4.article.subtitle': "Vielen Dank dafür, dass du uns dabei hilfst diesen Event zu etwas besonderen für alle Rollenspieler zu machen. <br />Wir prüfen deine Registrierung und würden uns in den nächsten Tagen wieder bei dir melden. <br /><br />Bis dahin alles Gute.<br />Das Luzerner Rollenspieltage Team"
  'en-EN':
    'registration.step-4.article.title': "Welcome Gamemaster"
    'registration.step-4.article.subtitle': "Thank you very much for helping us making this event a special one for every role player. <br />We will check your registration and come back to you in the next couple of days.<br />Have a good time, till we meet again.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"

