status: wip
context:
  sizes:
    -
      size: '64px'
    -
      size: '32px'
    -
      size: '16px'
  items:
    -
      label: 'Light'
      family: 'Frutiger'
      weight: '300'
    -
      label: 'Roman'
      family: 'Frutiger'
      weight: '400'
    -
      label: 'Bold'
      family: 'Frutiger'
      weight: '700'