status: published
context:
  emotion:
    figure:
      figure-class: "emotion"
      picture:
        picture-title: "Welcome to Luzerner Rollenspieltage"
        picture-i18n: ""
        picture-sources:
          -
            source: "/images/cover-dice-bag.jpg"
        image:
          image-alt: "Welcome to Luzerner Rollenspieltage"
          image-i18n: ""
          # image-class: ""
          image-source: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
          image-lazyload: "/images/cover-dice-bag.jpg"
  logo:
    icon:
      icon-name: "LuzernerRollenspieltag"
      icon-class: "logo"
