status: published
context:
  step-1:
    form:
      form-name: "ContactUs"
      form-action: "http://localhost:3000/rest/form.json"
      form-method: "get"
      form-class: "step-1 contact-step active"
      form-items:
        -
          fieldset:
            fieldset-items:
              # -
              #   form-row:
              #     -
              #       form-wrapper:
              #         form-wrapper-class: "col-m-12"
              #         article:
              #           main:
              #             article-body: "<p>To send as a message please enter your name and email. Those fields are mandatory.</p>"
              #             article-body-i18n: "contact.step-1.article.body"
              -
                form-row:
                  -
                    form-wrapper:
                      form-wrapper-class: "col-m-12"
                      input:
                        label:
                          label-for: "contact-name"
                          label-text: "Your Firstname, Lastname"
                          label-text-i18n: "contact.step-1.input.name"
                        input-id: "contact-name"
                        input-name: "ContactUs[name]"
                        input-placeholder: "Your Firstname, Lastname"
                        input-i18n: "contact.step-1.input.name"
                        input-required: true
                        input-class: ""
                        # Don't need for text > input-type: "text"
                        input-role: "input"
                        input-autocomplete: "name"
              -
                form-row:
                  -
                    form-wrapper:
                      form-wrapper-class: "col-m-12"
                      input:
                        label:
                          label-for: "contact-email"
                          label-text: "Your Email"
                          label-text-i18n: "contact.step-1.email.name"
                        input-id: "contact-email"
                        input-name: "ContactUs[email]"
                        input-placeholder: "Your Email"
                        input-i18n: "contact.step-1.email.name"
                        input-required: true
                        input-class: ""
                        input-type: "email"
                        input-role: "input"
                        input-autocomplete: "email"
              -
                form-row:
                  -
                    form-wrapper:
                      form-wrapper-class: "col-m-12"
                      textarea:
                        label:
                          label-for: "contact-message"
                          label-text: "Your message"
                          label-text-i18n: "contact.step-1.input.message"
                        textarea-id: "contact-message"
                        textarea-name: "ContactUs[message]"
                        textarea-placeholder: "Your message"
                        textarea-i18n: "contact.step-1.input.message"
                        textarea-required: true
                        textarea-class: ""
                        textarea-role: "textarea"
        -
          fieldset:
            fieldset-class: "hidden"
            fieldset-items:
              -
                form-row:
                  -
                    form-wrapper:
                      input:
                        input-name: "ContactUs[language]"
                        input-class: "hidden"
                        input-type: "hidden"
        -
          fieldset:
            fieldset-items:
              -
                form-row:
                  -
                    form-wrapper:
                      form-wrapper-class: "col-m-12 align-center"
                      button:
                        label:
                          label-text: "Send us your message"
                          label-text-i18n: "contact.step-1.button.next"
                        button-class: "submit-group"
                        button-type: "submit"
                        button-role: "button"
i18n:
  'de-DE':
    # 'contact.step-1.article.body': "<p>Um uns eine Nachricht zu senden trage bitte deinen Namen und deine Email ein. Dies sind Pflichteingaben.</p>"
    'contact.step-1.input.name': "Dein Vorname, Nachname"
    'contact.step-1.input.name.error': "Bitte trage deinen Namen ein"
    'contact.step-1.email.name': "Deine E-Mail"
    'contact.step-1.input.email.error.1': "Bitte trage deine E-Mail ein"
    'contact.step-1.input.email.error.2': "Die E-Mail sieht nicht korrekt aus"
    'contact.step-1.input.message': "Deine Nachricht"
    'contact.step-1.input.message.error': "Bitte trage deine Nachricht ein"
    'contact.step-1.button.next': "Sende uns deine Nachricht"
  'en-EN':
    # 'contact.step-1.article.body': "<p>To send as a message please enter your name and email. Those fields are mandatory.</p>"
    'contact.step-1.input.name': "Your Firstname, Lastname"
    'contact.step-1.input.name.error': "Please enter your Name"
    'contact.step-1.email.name': "Your Email"
    'contact.step-1.input.email.error.1': "Please enter your Email"
    'contact.step-1.input.email.error.2': "Email doesn't look correct"
    'contact.step-1.input.message': "Your message"
    'contact.step-1.input.message.error': "Please enter your Message"
    'contact.step-1.button.next': "Send us your message"

