status: published
context:
  step-2:
    panel-class: "step-2 contact-step"
    article:
      header:
        article-title: "Message recieved"
        article-title-i18n: "contact.step-2.article.title"
        article-title-tag: "h3"
        article-subtitle: "Thank you very much. We looking forward to answer your message.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"
        article-subtitle-i18n: "contact.step-2.article.subtitle"
i18n:
  'de-DE':
    'contact.step-2.article.title': "Nachricht erhalten"
    'contact.step-2.article.subtitle': "Vielen Dank für deine Nachricht. Wir freuen uns darauf dir eine rasche Antwort senden zu können.<br /><br />Beste Grüsse<br />Das Luzerner Rollenspieltage Team"
  'en-EN':
    'contact.step-2.article.title': "Message recieved"
    'contact.step-2.article.subtitle': "Thank you very much. We looking forward to answer your message.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"

