status: ready
context:
  label:
    label-text: "Link Label Text"
    label-text-i18n: "label.text.demo"
    icon:
      icon-name: "arrow-right"
      icon-pos: "before"
      icon-class: "icon-xs"
i18n:
  'de-DE':
    'label.text.demo': "Link Label Text (DE)"
  'en-EN':
    'label.text.demo': "Link Label Text (EN)"

