status: ready
context:
  image:
    image-alt: "Image alternative text"
    image-class: "example-image-class"
    image-source: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
    image-lazyload: "https://picsum.photos/2480/2048/?random&blur"
