status: published
context:
  article-info-config:
    article:
      header:
        article-title: "Infos"
        article-title-i18n: "panel3.article.info.title"
        article-title-tag: "h3"
      main:
        article-body: "<p>The Lucerne Role-Playing Day will take place on Saturday, 6th October 2018. We open the gates at midday and the first rounds begin at one o'clock.</p><p>Time: Saturday, 1pm to Sunday, 1am<br />Admission: 5 CHF per person / for game masters admission is free<br />Address: Pfarrei St. Johannes, Schadrätistrasse 26, 6006 Lucerne</p><p>From the Lucerne train station, the location is easily reached in 15 minutes by bus 8 (Würzenbachmatte) or bus 14 (Schlösslirain).</p><p>If you would like to stay overnight in Lucerne, we are happy to help you plan your stay. Please contact us via the contact form.</p>"
        article-body-i18n: "panel3.article.info.body"
  icon:
    icon-name: "arrow-right"
    icon-class: "icon-xs"
i18n:
  'de-DE':
    'panel3.article.info.title': "Infos"
    'panel3.article.info.body': "<p>Der Luzerner Rollenspieltag findet am Samstag, 6. Oktober 2018, statt. Wir öffnen die Tore ab 12 Uhr, die ersten Spielrunden beginnen um 13 Uhr.</p><p>Spielzeiten: Samstag, 13 Uhr bis Sonntag, 1 Uhr<br />Eintritt: 5 Franken pro Person / für Spielleiter ist der Eintritt gratis<br />Adresse: Pfarrei St. Johannes, Schädrütistrasse 26, 6006 Luzern</p><p>Vom Bahnhof Luzern sind die Räumlichkeiten bequem in 15 Minuten erreichbar per Bus 8 (Würzenbachmatte) oder Bus 14 (Schlösslirain).</p><p>Wenn du von weiterher kommst und gerne stressfrei in Luzern übernachten möchtest, helfen wir dir gerne dabei deinen Aufenthalt zu planen. <br /><a href='#page5'>Melde dich doch bitte über das Kontaktformular.</a></p>"
  'en-EN':
    'panel3.article.info.title': "Infos"
    'panel3.article.info.body': "<p>The Lucerne Role-Playing Day will take place on Saturday, 6th October 2018. We open the gates at midday and the first rounds begin at one o'clock.</p><p>Time: Saturday, 1pm to Sunday, 1am<br />Admission: 5 CHF per person / for game masters admission is free<br />Address: Pfarrei St. Johannes, Schadrätistrasse 26, 6006 Lucerne</p><p>From the Lucerne train station, the location is easily reached in 15 minutes by bus 8 (Würzenbachmatte) or bus 14 (Schlösslirain).</p><p>If you would like to stay overnight in Lucerne, we are happy to help you plan your stay. <br /><a href='#page5'>Please contact us via the contact form.</a></p>"