status: published
context:
  step-3:
    panel-class: "step-3 registration-step"
    article:
      article-hide-small: true
      article-title: "Welcome Player"
      article-title-i18n: "registration.player.step-3.article.title"
      article-title-tag: "h3"
      article-subtitle: "Thank you very much for your registration. <br />We looking forward to welcome you as Player to this special event.<br />Have a good time.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"
      article-subtitle-i18n: "registration.player.step-3.article.subtitle"
i18n:
  'de-DE':
    'registration.player.step-3.article.title': "Herzlich Willkommen als Spieler"
    'registration.player.step-3.article.subtitle': "Vielen Dank für deine Anmeldung. <br />Wir freuen uns schon darauf dich willkommen zu heissen zu diesem besonderen Event.<br /><br />Beste Grüsse<br />Dein Luzerner Rollenspieltage Team"
  'en-EN':
    'registration.player.step-3.article.title': "Welcome Player"
    'registration.player.step-3.article.subtitle': "Thank you very much for your registration. <br />We looking forward to welcome you as Player to this special event.<br />Have a good time.<br /><br />Best<br />Your Luzerner Rollenspieltage Team"

