status: published
context:
  step-2:
    form:
      form-name: "Playergames"
      form-action: "http://localhost:3000/rest/form.json"
      form-method: "get"
      form-class: "step-2 registration-step"
      form-items:
        -
          fieldset:
            fieldset-legend: "Please choose your Games"
            fieldset-legend-i18n: "registration.player.step-2.fieldset"
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12 form-group"
                      article:
                        article-hide-header: true
                        article-body: "<p>Please select your prevered games:</p>"
                        article-body-i18n: "registration.player.step-2.article.game"
                        article-hide-footer: true
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12"
                      fieldset:
                        fieldset-legend: "Please choose your game at the afternoon"
                        fieldset-legend-i18n: "registration.player.step-2.fieldset.time1"
                        fieldset-items:
                          -
                            group-row:
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-m-6"
                                  selector:
                                    label:
                                      label-for: "mygame-1-3"
                                      label-text: "from 1 p.m. to 3 p.m."
                                      label-text-i18n: "registration.player.step-2.choose-1-3"
                                    selector-role: "select"
                                    selector-id: "mygame-1-3"
                                    selector-name: "Playergames[mygame-1-3]"
                                    selector-class: "games-selector start-13"
                                    option-items:
                                      -
                                        option-value: "-1"
                                        option-label: "from 1 p.m. to 3 p.m."
                                        option-i18n: "registration.player.step-2.choose-1-3"
                                    navigation:
                                      # navigation-class: "example-class"
                                      navigation-wrap: true
                                      navigation-items:
                                        -
                                          link:
                                            link-href: "#"
                                            label:
                                              label-text: "from 1 p.m. to 3 p.m."
                                              label-text-i18n: "registration.player.step-2.choose-1-3"
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-m-6"
                                  selector:
                                    label:
                                      label-for: "mygame-3-5"
                                      label-text: "from 3 p.m. to 5 p.m."
                                      label-text-i18n: "registration.player.step-2.choose-3-5"
                                    selector-role: "select"
                                    selector-id: "mygame-3-5"
                                    selector-name: "Playergames[mygame-3-5]"
                                    selector-class: "games-selector start-15"
                                    option-items:
                                      -
                                        option-value: "-1"
                                        option-label: "from 3 p.m. to 5 p.m."
                                        option-i18n: "registration.player.step-2.choose-3-5"
                                    navigation:
                                      # navigation-class: "example-class"
                                      navigation-wrap: true
                                      navigation-items:
                                        -
                                          link:
                                            link-href: "#"
                                            label:
                                              label-text: "from 3 p.m. to 5 p.m."
                                              label-text-i18n: "registration.player.step-2.choose-3-5"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12"
                      fieldset:
                        fieldset-legend: "Please choose your game at the evening"
                        fieldset-legend-i18n: "registration.player.step-2.fieldset.time2"
                        fieldset-items:
                          -
                            group-row:
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-m-6"
                                  selector:
                                    label:
                                      label-for: "mygame-5-7"
                                      label-text: "from 5 p.m. to 7 p.m."
                                      label-text-i18n: "registration.player.step-2.choose-5-7"
                                    selector-role: "select"
                                    selector-id: "mygame-5-7"
                                    selector-name: "Playergames[mygame-5-7]"
                                    selector-class: "games-selector start-17"
                                    option-items:
                                      -
                                        option-value: "-1"
                                        option-label: "from 5 p.m. to 7 p.m."
                                        option-i18n: "registration.player.step-2.choose-5-7"
                                    navigation:
                                      # navigation-class: "example-class"
                                      navigation-wrap: true
                                      navigation-items:
                                        -
                                          link:
                                            link-href: "#"
                                            label:
                                              label-text: "from 5 p.m. to 7 p.m."
                                              label-text-i18n: "registration.player.step-2.choose-5-7"
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-m-6"
                                  selector:
                                    label:
                                      label-for: "mygame-7-9"
                                      label-text: "from 7 p.m. to 9 p.m."
                                      label-text-i18n: "registration.player.step-2.choose-7-9"
                                    selector-role: "select"
                                    selector-id: "mygame-7-9"
                                    selector-name: "Playergames[mygame-7-9]"
                                    selector-class: "games-selector start-19"
                                    option-items:
                                      -
                                        option-value: "-1"
                                        option-label: "from 7 p.m. to 9 p.m."
                                        option-i18n: "registration.player.step-2.choose-7-9"
                                    navigation:
                                      # navigation-class: "example-class"
                                      navigation-wrap: true
                                      navigation-items:
                                        -
                                          link:
                                            link-href: "#"
                                            label:
                                              label-text: "from 7 p.m. to 9 p.m."
                                              label-text-i18n: "registration.player.step-2.choose-7-9"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12"
                      fieldset:
                        fieldset-legend: "Please choose your game at night"
                        fieldset-legend-i18n: "registration.player.step-2.fieldset.time3"
                        fieldset-items:
                          -
                            group-row:
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-m-6"
                                  selector:
                                    label:
                                      label-for: "mygame-9-11"
                                      label-text: "from 9 p.m. to 11 p.m."
                                      label-text-i18n: "registration.player.step-2.choose-9-11"
                                    selector-role: "select"
                                    selector-id: "mygame-9-11"
                                    selector-name: "Playergames[mygame-9-11]"
                                    selector-class: "games-selector start-21"
                                    option-items:
                                      -
                                        option-value: "-1"
                                        option-label: "from 9 p.m. to 11 p.m."
                                        option-i18n: "registration.player.step-2.choose-9-11"
                                    navigation:
                                      # navigation-class: "example-class"
                                      navigation-wrap: true
                                      navigation-items:
                                        -
                                          link:
                                            link-href: "#"
                                            label:
                                              label-text: "from 9 p.m. to 11 p.m."
                                              label-text-i18n: "registration.player.step-2.choose-9-11"
                              -
                                group-wrapper:
                                  group-wrapper-class: "col-m-6"
                                  selector:
                                    label:
                                      label-for: "mygame-11-1"
                                      label-text: "from 11 p.m. to 1 a.m."
                                      label-text-i18n: "registration.player.step-2.choose-11-1"
                                    selector-role: "select"
                                    selector-id: "mygame-11-1"
                                    selector-name: "Playergames[mygame-11-1]"
                                    selector-class: "games-selector start-23"
                                    option-items:
                                      -
                                        option-value: "-1"
                                        option-label: "from 11 p.m. to 1 a.m."
                                        option-i18n: "registration.player.step-2.choose-11-1"
                                    navigation:
                                      # navigation-class: "example-class"
                                      navigation-wrap: true
                                      navigation-items:
                                        -
                                          link:
                                            link-href: "#"
                                            label:
                                              label-text: "from 11 p.m. to 1 a.m."
                                              label-text-i18n: "registration.player.step-2.choose-11-1"
        -
          fieldset:
            fieldset-class: "hidden"
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      input:
                        input-name: "Player[language]"
                        input-class: "hidden"
                        input-type: "hidden"
                  -
                    group-wrapper:
                      input:
                        input-name: "Player[id]"
                        input-class: "hidden"
                        input-type: "hidden"
        -
          fieldset:
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-xs-12"
                      input:
                        label:
                          label-for: "coc"
                          label-text: "I have read and accept the <a href='./code-of-conduct.html' target='blank'>Code of Conduct</a>"
                          label-text-i18n: "registration.player.step-2.input.coc"
                        input-id: "coc"
                        input-name: "Playergames[coc]"
                        input-required: true
                        input-class: ""
                        input-type: "checkbox"
                        input-role: "checkbox"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-s-6"
                      button-link:
                        link:
                          label:
                            label-text: "Back to previous form"
                            label-text-i18n: "registration.player.step-2.button.previous"
                          link-class: "button-link back-link"
                          link-href: "#form-1"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-s-6 align-right"
                      button:
                        label:
                          label-text: "Register for those games"
                          label-text-i18n: "registration.player.step-2.button.next"
                        button-class: "submit-group"
                        button-type: "submit"
                        button-role: "button"
i18n:
  'de-DE':
    'registration.player.step-2.fieldset': "Spielauswahl"
    'registration.player.step-2.article.game': "<p>Bitte wähle deine Spiele:</p>"
    'registration.player.step-2.fieldset.time1': "Bitte wähle deine Spiele am Nachmittag"
    'registration.player.step-2.fieldset.time2': "Bitte wähle deine Spiele am Abend"
    'registration.player.step-2.fieldset.time3': "Bitte wähle deine Spiele in der Nacht"
    'registration.player.step-2.choose-1-3': "von 13 bis 15 Uhr"
    'registration.player.step-2.choose-3-5': "von 15 bis 17 Uhr"
    'registration.player.step-2.choose-5-7': "von 17 bis 19 Uhr"
    'registration.player.step-2.choose-7-9': "von 19 bis 21 Uhr"
    'registration.player.step-2.choose-9-11': "von 21 bis 23 Uhr"
    'registration.player.step-2.choose-11-1': "von 23 bis 1 Uhr"
    'registration.player.step-2.players': "{1} Plätze frei"
    'registration.player.step-2.button.previous': "Zurück zur vorherigen Form"
    'registration.player.step-2.button.next': "Für Spiele anmelden"
    'registration.player.step-2.input.coc': "Ich habe den <a href='./code-of-conduct.html' target='blank'>Code of Conduct</a> gelesen und aktzeptiere diesen"
    'registration.player.step-2.input.coc.error': "Bitte aktzeptiere unseren Code of Conduct"
    'registration.player.step-2.input.opt.1': "Einsteigerfreundlich"
    'registration.player.step-2.input.opt.2': "Kinderfreundlich"
    'registration.player.step-2.input.opt.3': "nur für Erwachsene"
    'registration.player.step-2.input.opt.4': "nur für Frauen"
  'en-EN':
    'registration.player.step-2.fieldset': "Game Selection"
    'registration.player.step-2.article.game': "<p>Please choose your games:</p>"
    'registration.player.step-2.fieldset.time1': "Please choose your game at the afternoon"
    'registration.player.step-2.fieldset.time2': "Please choose your game at the evening"
    'registration.player.step-2.fieldset.time3': "Please choose your game at night"
    'registration.player.step-2.choose-1-3': "from 1 p.m. to 3 p.m."
    'registration.player.step-2.choose-3-5': "from 3 p.m. to 5 p.m."
    'registration.player.step-2.choose-5-7': "from 5 p.m. to 7 p.m."
    'registration.player.step-2.choose-7-9': "from 7 p.m. to 9 p.m."
    'registration.player.step-2.choose-9-11': "from 9 p.m. to 11 p.m."
    'registration.player.step-2.choose-11-1': "from 11 p.m. to 1 a.m."
    'registration.player.step-2.players': "{1} spots left"
    'registration.player.step-2.button.previous': "Back to previous form"
    'registration.player.step-2.button.next': "Register for those games"
    'registration.player.step-2.input.coc': "I have read and accept the <a href='./code-of-conduct.html' target='blank'>Code of Conduct</a>"
    'registration.player.step-2.input.coc.error': "Please accept our Code of Conduct"
    'registration.player.step-2.input.opt.1': "For Beginners"
    'registration.player.step-2.input.opt.2': "For Kids"
    'registration.player.step-2.input.opt.3': "Adults only"
    'registration.player.step-2.input.opt.4': "Womens only"

