status: published
context:
  step-2:
    form:
      form-name: "Playergames"
      form-action: "http://localhost:3000/rest/form.json"
      form-method: "get"
      form-class: "step-2 registration-step"
      form-items:
        -
          fieldset:
            fieldset-legend: "Please choose your Games"
            fieldset-legend-i18n: "registration.player.step-2.fieldset"
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-m-12 form-group"
                      article:
                        article-hide-header: true
                        article-body: "<p>Please select your prevered game slots:</p>"
                        article-body-i18n: "registration.player.step-2.article.game"
                        article-hide-footer: true

        -
          fieldset:
            fieldset-class: "hidden"
            fieldset-items:
              -
                group-row:
                  -
                    group-wrapper:
                      input:
                        input-name: "Player[language]"
                        input-class: "hidden"
                        input-type: "hidden"
                  -
                    group-wrapper:
                      input:
                        input-name: "Player[id]"
                        input-class: "hidden"
                        input-type: "hidden"
              -
                group-row:
                  -
                    group-wrapper:
                      group-wrapper-class: "col-s-6"
                      button-link:
                        link:
                          label:
                            label-text: "Back to previous form"
                            label-text-i18n: "registration.player.step-2.button.previous"
                          link-class: "button-link back-link"
                          link-href: "#form-1"
                  -
                    group-wrapper:
                      group-wrapper-class: "col-s-6 align-right"
                      button:
                        label:
                          label-text: "Submit your game"
                          label-text-i18n: "registration.player.step-2.button.next"
                        button-class: "submit-group"
                        button-type: "submit"
                        button-role: "button"
i18n:
  'de-DE':
    'registration.player.step-2.fieldset': "Spielauswahl"
    'registration.player.step-2.article.game': "<p>Bitte wähle deine gewünschten Spiel Slots aus:</p>"
    'registration.player.step-2.button.previous': "Zurück zur vorherigen Form"
    'registration.player.step-2.button.next': "Spielanmeldungen eintragen"
  'en-EN':
    'registration.player.step-2.fieldset': "Game Selection"
    'registration.player.step-2.article.game': "<p>Please select your prevered game slots:</p>"
    'registration.player.step-2.button.previous': "Back to previous form"
    'registration.player.step-2.button.next': "Submit your game registrations"

