status: ready
context:
  selector:
    label:
      label-for: "demo-select-1"
      label-text: "Demo Select Field 1"
      # label-text-i18n: "label.text.demo"
    selector-role: "select"
    selector-id: "demo-selector-1"
    selector-name: "demo[selector-1]"
    selector-class: "example-selector-class col-m-6"
    option-items:
      -
        option-value: "-1"
        option-label: "Demo Select Field 1"
        # option-i18n: "label.text.demo"
      -
        option-value: "1"
        option-label: "Opt 1"
        # option-i18n: "option.demo.1"
      -
        option-value: "2"
        option-label: "Opt 2"
        # option-i18n: "option.demo.2"
      -
        option-value: "3"
        option-label: "Opt 3"
        # option-i18n: "option.demo.3"
    navigation:
      navigation-class: "example-class"
      navigation-wrap: true
      navigation-items:
        -
          link:
            link-href: "#"
            label:
              label-text: "Demo Select Field 1"
              # label-text-i18n: "navigation.link.label.text.demo.1"
        -
          link:
            link-href: "#"
            label:
              label-text: "Opt 1"
              # label-text-i18n: "navigation.link.label.text.demo.2"
        -
          link:
            link-href: "#"
            label:
              label-text: "Opt 2"
              # label-text-i18n: "navigation.link.label.text.demo.3"
        -
          link:
            link-href: "#"
            label:
              label-text: "Opt 3"
              # label-text-i18n: "navigation.link.label.text.demo.3"
# i18n:
#   'de-DE':
#     'label.text.demo': "Demo Select Field 1 (DE)"
#     'option.demo.1': "Opt 1 (DE)"
#     'option.demo.2': "Opt 2 (DE)"
#     'option.demo.3': "Opt 3 (DE)"
#   'en-EN':
#     'label.text.demo': "Demo Select Field 1 (EN)"
#     'option.demo.1': "Opt 1 (EN)"
#     'option.demo.2': "Opt 2 (EN)"
#     'option.demo.3': "Opt 3 (EN)"